"""
JobHunter License Server — runs on Render free tier.

Single Flask app exposing:

  Public endpoint:
    POST /api/activate           — installer phones home with key + fingerprint
                                   server validates, marks key used, returns signed token

  Admin endpoints (require X-Admin-Token header):
    POST /api/admin/keys         — generate a new key
    GET  /api/admin/keys         — list all keys (with status)
    GET  /api/admin/keys/<key>   — inspect one key (binding details)
    DELETE /api/admin/keys/<key> — revoke (soft delete — never destructive)
    GET  /api/admin/stats        — overall counts

Storage: SQLite file at /var/data/licenses.db (Render persistent disk).
Falls back to ./licenses.db locally.

Signing: Ed25519. Private key read from PRIVATE_KEY_PEM env var on Render.
"""
from __future__ import annotations

import base64
import json
import os
import secrets
import sqlite3
import time
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path

from flask import Flask, request, jsonify, abort
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey, Ed25519PublicKey,
)


# ── Config ────────────────────────────────────────────────────────────────────
# Render mounts persistent disks at /var/data when configured in render.yaml.
DB_DIR = Path(os.environ.get("LICENSE_DB_DIR", "/var/data"))
if not DB_DIR.exists() or not os.access(DB_DIR, os.W_OK):
    DB_DIR = Path(__file__).resolve().parent
DB_PATH = DB_DIR / "licenses.db"

ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "")
PRIVATE_KEY_PEM = os.environ.get("PRIVATE_KEY_PEM", "")
# The matching public key. Embedded in the JobHunter client so it can verify
# the signed activation tokens we return. Generated by tools/generate_keypair.py.
PUBLIC_KEY_PEM = os.environ.get("PUBLIC_KEY_PEM", "")

# Activation token TTL — how long the locally-cached license is considered valid
# before the app would want to phone home again. Default: practically forever
# (10 years). The user wanted no recurring phone-home, so this is high by design.
ACTIVATION_TTL_DAYS = int(os.environ.get("ACTIVATION_TTL_DAYS", "3650"))


# ── DB ────────────────────────────────────────────────────────────────────────
SCHEMA = """
CREATE TABLE IF NOT EXISTS licenses (
    key              TEXT PRIMARY KEY,
    customer_name    TEXT,
    customer_email   TEXT,
    notes            TEXT,
    created_at       TEXT NOT NULL,
    expires_at       TEXT,                -- after this date, key cannot be activated
    used             INTEGER DEFAULT 0,
    activated_at     TEXT,
    fingerprint_hash TEXT,
    activation_ip    TEXT,
    revoked          INTEGER DEFAULT 0,
    revoked_at       TEXT,
    revoke_reason    TEXT
);

CREATE INDEX IF NOT EXISTS idx_licenses_used ON licenses(used);
CREATE INDEX IF NOT EXISTS idx_licenses_revoked ON licenses(revoked);

CREATE TABLE IF NOT EXISTS activation_attempts (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    key             TEXT,
    fingerprint     TEXT,
    ip              TEXT,
    user_agent      TEXT,
    success         INTEGER,
    error           TEXT,
    attempted_at    TEXT NOT NULL
);
"""


@contextmanager
def _conn():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    c = sqlite3.connect(str(DB_PATH), timeout=30, isolation_level=None)
    c.row_factory = sqlite3.Row
    c.execute("PRAGMA journal_mode=WAL")
    try:
        yield c
    finally:
        c.close()


def init_db():
    with _conn() as c:
        c.executescript(SCHEMA)


# ── Crypto helpers ────────────────────────────────────────────────────────────
def _load_private_key() -> Ed25519PrivateKey:
    if not PRIVATE_KEY_PEM:
        raise RuntimeError("PRIVATE_KEY_PEM env var is not set on the server.")
    return serialization.load_pem_private_key(
        PRIVATE_KEY_PEM.encode("utf-8"), password=None
    )


def _sign_payload(payload: dict) -> str:
    """Return base64(payload_json) . base64(signature)."""
    body = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    key = _load_private_key()
    sig = key.sign(body)
    return (
        base64.urlsafe_b64encode(body).decode("ascii").rstrip("=")
        + "."
        + base64.urlsafe_b64encode(sig).decode("ascii").rstrip("=")
    )


def _new_key() -> str:
    """Generate a human-friendly key: JHTR-XXXX-XXXX-XXXX-XXXX (uppercase A-Z, 2-9)."""
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"  # no I/O/0/1 for readability
    groups = ["".join(secrets.choice(alphabet) for _ in range(4)) for _ in range(4)]
    return "JHTR-" + "-".join(groups)


def _admin_required():
    token = request.headers.get("X-Admin-Token", "")
    if not ADMIN_TOKEN:
        abort(500, description="ADMIN_TOKEN not configured on server.")
    if not secrets.compare_digest(token, ADMIN_TOKEN):
        abort(401, description="Bad admin token.")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# ── App ───────────────────────────────────────────────────────────────────────
app = Flask(__name__)


@app.before_request
def _ensure_db():
    # Cheap idempotent init on each request — sqlite handles "IF NOT EXISTS".
    init_db()


@app.route("/")
def root():
    return jsonify({
        "service": "JobHunter License Server",
        "status": "ok",
        "time": _now_iso(),
    })


@app.route("/healthz")
def healthz():
    return "ok", 200


# ── Public: activate a key ────────────────────────────────────────────────────
@app.route("/api/activate", methods=["POST"])
def activate():
    data = request.get_json(silent=True) or {}
    key = (data.get("key") or "").strip().upper()
    fingerprint = (data.get("fingerprint") or "").strip()
    ua = request.headers.get("User-Agent", "")[:200]
    ip = request.headers.get("X-Forwarded-For", request.remote_addr or "")[:64]

    if not key or not fingerprint:
        _log_attempt(key, fingerprint, ip, ua, success=False, error="missing_fields")
        return jsonify({"ok": False, "error": "missing_fields"}), 400

    with _conn() as c:
        row = c.execute("SELECT * FROM licenses WHERE key = ?", (key,)).fetchone()

        if not row:
            _log_attempt(key, fingerprint, ip, ua, success=False, error="not_found")
            return jsonify({"ok": False, "error": "key_not_found",
                            "message": "Key not recognised. Check for typos or contact rakshi886@gmail.com."}), 404

        if row["revoked"]:
            _log_attempt(key, fingerprint, ip, ua, success=False, error="revoked")
            return jsonify({"ok": False, "error": "revoked",
                            "message": "This key has been revoked. Contact rakshi886@gmail.com."}), 403

        if row["expires_at"]:
            try:
                exp = datetime.fromisoformat(row["expires_at"])
                if datetime.now(timezone.utc) > exp:
                    _log_attempt(key, fingerprint, ip, ua, success=False, error="expired")
                    return jsonify({"ok": False, "error": "expired",
                                    "message": "This key has expired. Contact rakshi886@gmail.com."}), 403
            except Exception:
                pass

        if row["used"]:
            # Special case: same fingerprint trying to re-activate — allow silently.
            if row["fingerprint_hash"] == fingerprint:
                token = _build_token(key, row["customer_name"] or "", fingerprint)
                _log_attempt(key, fingerprint, ip, ua, success=True, error="reactivation_same_device")
                return jsonify({"ok": True, "token": token,
                                "customer_name": row["customer_name"],
                                "message": "Already activated on this device — token re-issued."})
            _log_attempt(key, fingerprint, ip, ua, success=False, error="already_used")
            return jsonify({
                "ok": False, "error": "already_used",
                "message": ("This key is already activated on a different device. "
                            "Contact rakshi886@gmail.com if you need a new one."),
            }), 403

        # ── Activate now ─────────────────────────────────────────────────────
        c.execute(
            """UPDATE licenses
                  SET used = 1,
                      activated_at = ?,
                      fingerprint_hash = ?,
                      activation_ip = ?
                WHERE key = ?""",
            (_now_iso(), fingerprint, ip, key),
        )
        token = _build_token(key, row["customer_name"] or "", fingerprint)
        _log_attempt(key, fingerprint, ip, ua, success=True)

    return jsonify({
        "ok": True,
        "token": token,
        "customer_name": row["customer_name"],
        "message": "Activated successfully.",
    })


def _build_token(key: str, customer_name: str, fingerprint: str) -> str:
    payload = {
        "key": key,
        "customer_name": customer_name,
        "fingerprint_hash": fingerprint,
        "activated_at": _now_iso(),
        "ttl_days": ACTIVATION_TTL_DAYS,
    }
    return _sign_payload(payload)


def _log_attempt(key, fingerprint, ip, ua, success, error=""):
    try:
        with _conn() as c:
            c.execute(
                """INSERT INTO activation_attempts
                       (key, fingerprint, ip, user_agent, success, error, attempted_at)
                       VALUES (?, ?, ?, ?, ?, ?, ?)""",
                (key, fingerprint[:64], ip, ua, 1 if success else 0, error, _now_iso()),
            )
    except Exception:
        pass  # logging is best-effort


# ── Admin endpoints ───────────────────────────────────────────────────────────
@app.route("/api/admin/keys", methods=["POST"])
def admin_create_key():
    _admin_required()
    data = request.get_json(silent=True) or {}
    customer_name = (data.get("customer_name") or "").strip()
    customer_email = (data.get("customer_email") or "").strip()
    notes = (data.get("notes") or "").strip()
    valid_days = data.get("valid_days")
    count = max(1, min(50, int(data.get("count") or 1)))

    expires_at = None
    if valid_days:
        try:
            expires_at = (
                datetime.now(timezone.utc) + timedelta(days=int(valid_days))
            ).isoformat(timespec="seconds")
        except Exception:
            expires_at = None

    created = []
    with _conn() as c:
        for _ in range(count):
            for _attempt in range(5):
                k = _new_key()
                try:
                    c.execute(
                        """INSERT INTO licenses
                               (key, customer_name, customer_email, notes,
                                created_at, expires_at)
                               VALUES (?, ?, ?, ?, ?, ?)""",
                        (k, customer_name, customer_email, notes, _now_iso(), expires_at),
                    )
                    created.append(k)
                    break
                except sqlite3.IntegrityError:
                    continue
    return jsonify({"ok": True, "keys": created, "count": len(created)})


@app.route("/api/admin/keys", methods=["GET"])
def admin_list_keys():
    _admin_required()
    status = request.args.get("status", "").lower()
    sql = "SELECT * FROM licenses"
    params = ()
    if status == "used":
        sql += " WHERE used = 1 AND revoked = 0"
    elif status == "available":
        sql += " WHERE used = 0 AND revoked = 0"
    elif status == "revoked":
        sql += " WHERE revoked = 1"
    sql += " ORDER BY created_at DESC LIMIT 500"

    with _conn() as c:
        rows = c.execute(sql, params).fetchall()
    return jsonify({"ok": True, "keys": [dict(r) for r in rows]})


@app.route("/api/admin/keys/<key>", methods=["GET"])
def admin_inspect_key(key: str):
    _admin_required()
    key = key.upper().strip()
    with _conn() as c:
        row = c.execute("SELECT * FROM licenses WHERE key = ?", (key,)).fetchone()
        if not row:
            return jsonify({"ok": False, "error": "not_found"}), 404
        attempts = c.execute(
            "SELECT * FROM activation_attempts WHERE key = ? ORDER BY id DESC LIMIT 20",
            (key,),
        ).fetchall()
    return jsonify({
        "ok": True,
        "key": dict(row),
        "recent_attempts": [dict(a) for a in attempts],
    })


@app.route("/api/admin/keys/<key>", methods=["DELETE"])
def admin_revoke_key(key: str):
    _admin_required()
    key = key.upper().strip()
    reason = (request.args.get("reason") or "").strip()[:200]
    with _conn() as c:
        cur = c.execute(
            """UPDATE licenses SET revoked = 1, revoked_at = ?, revoke_reason = ?
                WHERE key = ?""",
            (_now_iso(), reason, key),
        )
        if cur.rowcount == 0:
            return jsonify({"ok": False, "error": "not_found"}), 404
    return jsonify({"ok": True, "revoked": key, "reason": reason})


@app.route("/api/admin/stats", methods=["GET"])
def admin_stats():
    _admin_required()
    with _conn() as c:
        total    = c.execute("SELECT COUNT(*) AS n FROM licenses").fetchone()["n"]
        used     = c.execute("SELECT COUNT(*) AS n FROM licenses WHERE used = 1 AND revoked = 0").fetchone()["n"]
        avail    = c.execute("SELECT COUNT(*) AS n FROM licenses WHERE used = 0 AND revoked = 0").fetchone()["n"]
        revoked  = c.execute("SELECT COUNT(*) AS n FROM licenses WHERE revoked = 1").fetchone()["n"]
        attempts = c.execute("SELECT COUNT(*) AS n FROM activation_attempts").fetchone()["n"]
        failed   = c.execute("SELECT COUNT(*) AS n FROM activation_attempts WHERE success = 0").fetchone()["n"]
    return jsonify({
        "ok": True,
        "total_keys": total, "used": used, "available": avail, "revoked": revoked,
        "total_attempts": attempts, "failed_attempts": failed,
    })


# ── Local dev entrypoint ──────────────────────────────────────────────────────
if __name__ == "__main__":
    init_db()
    port = int(os.environ.get("PORT", "8080"))
    app.run(host="0.0.0.0", port=port, debug=False)
